@ApiService_HostAddress = http://localhost:5402
@PythonService_HostAddress = https://localhost:58508

GET {{ApiService_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{PythonService_HostAddress}}/agents/hello-world
Accept: application/json

###

POST {{PythonService_HostAddress}}/agents/count-letters
Accept: application/json

{
    "question": "How many `r` are there in the word strawberry?"
}
