@ApiService_HostAddress = http://localhost:5402
@PythonService_HostAddress = https://localhost:9443

###
GET {{ApiService_HostAddress}}/weatherforecast/
Accept: application/json

###
POST {{ApiService_HostAddress}}/countLetters
Accept: application/json
Content-Type: application/json

{
    "question": "I want to know the square root of the number of times the letter `r` is found in `Strawberry`?"
}

###
POST {{ApiService_HostAddress}}/countLetters-a2a
Accept: application/json
Content-Type: application/json

{
    "question": "I want to know the square root of the number of times the letter `r` is found in `Strawberry`?"
}

###

GET {{PythonService_HostAddress}}/agents/hello-world
Accept: application/json

###

POST {{PythonService_HostAddress}}/agents/count-letters
Accept: application/json

{
    "question": "How many `r` are there in the word strawberry?"
}

###
POST {{PythonService_HostAddress}}/agents/count-letters
Accept: application/json

{
    "question": "I want to know the square root of the number of times the letter `r` is found in `Strawberry`?"
}

### Count Letters - Agent Card
GET {{PythonService_HostAddress}}/agents/count-letters/.well-known/agent-card.json
Accept: application/json
