@ApiService_HostAddress = http://localhost:5402
@PythonService_HostAddress = https://localhost:55415

GET {{ApiService_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{PythonService_HostAddress}}/agents/hello-world
Accept: application/json
